### ISSUE TITLE
Template deployment in hunting demo fails

### ISSUE THREAD

**Issue by azureandbeyond** [peterschen/blog#13]
Template deployment fails with the following error message:

> Unable to download deployment content from 'https://raw.githubusercontent.com/peterschen/blog/master//samples/monitoring-pipeline/logicapp.json'. The tracking Id is 'bb48e26b-8ff2-4662-b0ac-39f31a3e733d'. Please see https://aka.ms/arm-deploy for usage details. (Code: InvalidContentLink)

Looks like there is a "/" too much at the end of line 165 of https://github.com/peterschen/blog/blob/8ab033067a055718f26e4b9fccd711ef95702994/samples/hunting-threats-with-asc/azuredeploy.json#L165

**Comment by peterschen** [comment]
This has been fixed.
